#!/usr/bin/env bash

# Get script directory.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )";
WORKSPACE_DIR="$(dirname $(dirname $SCRIPT_DIR))";

# Check if the target process is already running.
PIDFILE=/tmp/dask-scheduler.pid
LOGFILE=/tmp/dask-scheduler.log
if [ -f $PIDFILE ]
then
    echo "Process already running. You would need to stop it before starting it again.";
    exit 0;
else
    
    # Activate the virtual environment.
    source $WORKSPACE_DIR/.venv/bin/activate;
    source $WORKSPACE_DIR/.env;

    # Create the var directory if it doesn't exist.
    mkdir -p $WORKSPACE_DIR/var;

    # Start the scheduler.
    nohup dask-scheduler --scheduler-file $WORKSPACE_DIR/var/scheduler-file.json > $LOGFILE & echo $! > $PIDFILE

fi
